# -*- coding: utf-8 -*-
"""英文译名修订表：科目号 -> 依据法文本义重译的英文。
仅收录「重复组」（子科目沿用父科目英文）及已确认错译的条目。
"""
FIX = {}

FIX.update({
# ---- 类别 1 长期资源 ----
'101': 'Share capital',
'1011': 'Share capital subscribed, not called up',
'1012': 'Share capital subscribed, called up, not paid',
'1013': 'Share capital subscribed, called up, paid, not amortised',
'1014': 'Share capital subscribed, called up, paid, amortised',
'1018': 'Share capital subscribed subject to special conditions',
'102': 'Endowment capital',
'1021': 'Initial endowment',
'1022': 'Additional endowments',
'1028': 'Other endowments',
'104': 'Owner current account',
'1041': 'Temporary contributions',
'1042': 'Current transactions',
'1043': 'Remuneration, taxes and other personal expenses',
'1047': 'Withdrawals for own consumption',
'1048': 'Other withdrawals',
'105': 'Share premiums',
'1051': 'Issue premiums',
'1052': 'Contribution premiums',
'1053': 'Merger premiums',
'1054': 'Conversion premiums',
'1058': 'Other premiums',
'106': 'Revaluation differences',
'1061': 'Statutory revaluation differences',
'1062': 'Discretionary revaluation differences',
'113': 'Regulated reserves',
'1131': 'Long-term net capital gains reserves',
'1132': 'Reserves for free share allocations to employees and managers',
'1133': 'Reserves arising from investment grants',
'1134': 'Reserves for securities giving access to share capital',
'1138': 'Other regulated reserves',
'118': 'Other reserves',
'1181': 'Discretionary reserves',
'1188': 'Sundry reserves',
'129': 'Retained earnings brought forward, debit balance',
'1291': 'Net loss to be carried forward',
'1292': 'Loss on deemed deferred depreciation',
'130': 'Result pending appropriation',
'1301': 'Profit pending appropriation',
'1309': 'Loss pending appropriation',
'138': 'Result of non-ordinary activities',
'1381': 'Merger result',
'1382': 'Result of partial contribution of assets',
'1383': 'Demerger result',
'1384': 'Liquidation result',
'141': 'Equipment grants',
'1411': 'State',
'1412': 'Regions',
'1413': 'Departments',
'1414': 'Municipalities and decentralised public authorities',
'1415': 'Public or mixed-ownership enterprises',
'1416': 'Private enterprises and organisations',
'1417': 'International organisations',
'1418': 'Other',
'15': 'Regulated provisions and similar funds',
'153': 'Regulated funds',
'1531': 'National fund',
'1532': 'Budget levy',
'155': 'Regulated provisions relating to non-current assets',
'1551': 'Reconstitution of mining and petroleum deposits',
'156': 'Regulated provisions relating to inventories',
'1561': 'Price increases',
'1562': 'Price fluctuations',
'161': 'Bond borrowings',
'1611': 'Ordinary bonds',
'1612': 'Convertible bonds',
'1613': 'Bonds redeemable in shares',
'1618': 'Other bond borrowings',
'165': 'Deposits and guarantees received',
'1651': 'Deposits',
'1652': 'Guarantees',
'166': 'Accrued interest on borrowings',
'1661': 'Accrued interest on bond borrowings',
'1662': 'Accrued interest on borrowings and debts to credit institutions',
'1663': 'Accrued interest on advances received from the State',
'1664': 'Accrued interest on advances received and blocked current accounts',
'1665': 'Accrued interest on deposits and guarantees received',
'1667': 'Accrued interest on advances subject to special conditions',
'1668': 'Accrued interest on other borrowings and debts',
'167': 'Advances subject to special conditions',
'1671': 'Blocked advances for capital increase',
'1672': 'Advances conditioned by the State',
'1673': 'Advances conditioned by other African organisations',
'1674': 'Advances conditioned by international organisations',
'168': 'Other borrowings and debts',
'1681': 'Capitalised life annuities',
'1682': 'Promissory notes',
'1683': 'Debts arising from borrowed securities',
'1684': 'Participating loans',
'1685': 'Employee profit sharing',
'1686': 'Borrowings and debts contracted with other third parties',
'176': 'Accrued interest on lease-purchase liabilities',
'1762': 'Accrued interest on property lease-purchase liabilities',
'1763': 'Accrued interest on movable lease-purchase liabilities',
'1764': 'Accrued interest on hire purchase liabilities',
'1768': 'Accrued interest on other lease-purchase liabilities',
'18': 'Liabilities related to participations, and liaison accounts of branches and joint ventures',
'181': 'Liabilities related to participations',
'1811': 'Liabilities related to participations, group',
'1812': 'Liabilities related to participations, outside the group',
'196': 'Provisions for pensions and similar obligations',
'1961': 'Provisions for pensions and similar obligations, retirement commitments',
'1962': 'Retirement plan assets',
'198': 'Other provisions for risks and charges',
'1981': 'Provisions for fines and penalties',
'1983': 'Provisions for self-insurance',
'1984': 'Provisions for dismantling and site restoration',
'1985': 'Provisions for deduction rights, gift vouchers and loyalty cards',
'1988': 'Other provisions for risks and charges',

# ---- 类别 2 固定资产 ----
'212': 'Patents, licences, concessions and similar rights',
'2121': 'Patents',
'2122': 'Licences',
'2123': 'Public service concessions',
'2128': 'Other concessions and similar rights',
'213': 'Software and websites',
'2131': 'Software',
'2132': 'Websites',
'218': 'Other intangible rights and assets',
'2181': 'Mineral resource exploration and evaluation costs',
'2182': 'Contract acquisition costs',
'2183': 'Customer files, manuals, newspaper and magazine titles',
'2184': 'Franchise costs',
'2188': 'Sundry intangible rights and assets',
'219': 'Intangible assets in progress',
'2191': 'Development costs',
'2193': 'Software',
'2198': 'Other intangible rights and assets',
'221': 'Agricultural and forestry land',
'2211': 'Land used for farming',
'2212': 'Land used for forestry',
'2218': 'Other land',
'222': 'Undeveloped land',
'2221': 'Building land',
'2228': 'Other undeveloped land',
'223': 'Land with buildings',
'2231': 'Land for industrial and agricultural buildings',
'2232': 'Land for administrative and commercial buildings',
'2234': 'Land for buildings used in other professional operations',
'2235': 'Land for buildings used in other non-professional operations',
'2238': 'Other land with buildings',
'224': 'Land development works',
'2241': 'Tree and shrub plantations',
'2245': 'Land improvements',
'2248': 'Other works',
'225': 'Quarry land and subsoil',
'2251': 'Quarries',
'226': 'Developed land',
'2261': 'Car parks',
'228': 'Other land',
'2281': 'Land of investment property',
'2285': 'Land of staff housing',
'2286': 'Lease-purchase land',
'2288': 'Other',
'229': 'Land improvements in progress',
'2291': 'Agricultural and forestry land',
'2292': 'Undeveloped land',
'2295': 'Quarry land and subsoil',
'2298': 'Other land',
'231': 'Buildings on own land',
'2311': 'Industrial buildings on own land',
'2312': 'Agricultural buildings on own land',
'2313': 'Administrative and commercial buildings on own land',
'2314': 'Staff housing buildings on own land',
'2315': 'Investment property on own land',
'2316': 'Lease-purchase buildings on own land',
'232': 'Buildings on third-party land',
'2321': 'Industrial buildings on third-party land',
'2322': 'Agricultural buildings on third-party land',
'2323': 'Administrative and commercial buildings on third-party land',
'2324': 'Staff housing buildings on third-party land',
'2325': 'Investment property on third-party land',
'2326': 'Lease-purchase buildings on third-party land',
'233': 'Infrastructure works',
'2331': 'Earth roads',
'2332': 'Railways',
'2333': 'Waterways',
'2334': 'Dams and dykes',
'2335': 'Airfield runways',
'2338': 'Other infrastructure works',
'234': 'Technical installations',
'2341': 'Specialised complex installations on own land',
'2342': 'Specialised complex installations on third-party land',
'2343': 'Specific-purpose installations on own land',
'2344': 'Specific-purpose installations on third-party land',
'2345': 'Building fittings and improvements',
'235': 'Office fittings',
'2351': 'General installations',
'2358': 'Other office fittings',
})

FIX.update({
# ---- 类别 2（续）----
'239': 'Buildings and installations in progress',
'2391': 'Buildings in progress',
'2392': 'Installations in progress',
'2393': 'Infrastructure works in progress',
'2394': 'Office fittings in progress',
'2395': 'Fittings and improvements',
'2398': 'Other installations in progress',
'241': 'Industrial and commercial plant and equipment',
'2411': 'Industrial equipment',
'2412': 'Industrial tools',
'2413': 'Commercial equipment',
'2414': 'Commercial tools',
'2416': 'Lease-purchase plant and equipment',
'242': 'Agricultural plant and equipment',
'2421': 'Agricultural equipment',
'2422': 'Agricultural tools',
'2426': 'Lease-purchase agricultural plant and equipment',
'244': 'Equipment and furniture',
'2441': 'Office equipment',
'2442': 'Computer equipment',
'2443': 'Office automation equipment',
'2444': 'Office furniture',
'2446': 'Lease-purchase equipment and furniture',
'2447': 'Equipment and furniture of staff housing',
'245': 'Transport equipment',
'2451': 'Motor vehicles',
'2452': 'Railway rolling stock',
'2453': 'Inland waterway and lagoon vessels',
'2454': 'Sea-going vessels',
'2455': 'Aircraft',
'2456': 'Lease-purchase transport equipment',
'2457': 'Horse-drawn vehicles',
'2458': 'Other transport equipment, bicycles, mopeds and motorcycles',
'246': 'Biological assets',
'2461': 'Draught livestock',
'2462': 'Breeding livestock',
'2463': 'Guard animals',
'2465': 'Agricultural plantations',
'2468': 'Other biological assets',
'247': 'Fittings and improvements to equipment and biological assets',
'2471': 'Fittings and improvements to equipment',
'2472': 'Fittings and improvements to biological assets',
'2478': 'Other fittings and improvements',
'248': 'Other equipment and furniture',
'2481': 'Collections and works of art',
'2488': 'Other equipment and furniture',
'249': 'Equipment and biological assets in progress',
'2491': 'Industrial and commercial plant and equipment in progress',
'2492': 'Agricultural plant and equipment in progress',
'2493': 'Returnable and identifiable packaging in progress',
'2494': 'Office equipment and furniture in progress',
'2495': 'Transport equipment in progress',
'2496': 'Biological assets in progress',
'2497': 'Fittings and improvements to equipment and biological assets in progress',
'2498': 'Other equipment in progress',
'27': 'Other financial assets',
'278': 'Sundry financial assets',
'2781': 'Sundry group receivables',
'2782': 'Sundry receivables outside the group',
'2784': 'Bank term deposits',
'2785': 'Gold and precious metals',
'2788': 'Other financial assets',
'271': 'Loans and receivables',
'2711': 'Participating loans',
'2712': 'Loans to shareholders',
'2713': 'Promissory notes',
'2714': 'Finance lease receivables',
'2715': 'Securities lent',
'2718': 'Other loans',
'272': 'Loans to employees',
'2721': 'Property loans',
'2722': 'Movable and installation loans',
'2728': 'Other loans for study expenses',
'273': 'Receivables from the State',
'2731': 'Guarantee retentions',
'2733': 'Regulated funds',
'2734': 'Receivables from the grantor',
'2738': 'Other receivables from the State',
'274': 'Long-term investment securities',
'2741': 'Portfolio activity investment securities',
'2742': 'Participating securities',
'2743': 'Investment certificates',
'2744': 'Units in mutual funds',
'2745': 'Bonds',
'2746': 'Own shares or units',
'2748': 'Other long-term investment securities',
'275': 'Deposits and guarantees paid',
'2751': 'Deposits for rent paid in advance',
'2752': 'Electricity deposits',
'2753': 'Water deposits',
'2754': 'Gas deposits',
'2755': 'Telephone, telex and fax deposits',
'2756': 'Guarantees on public contracts',
'2757': 'Guarantees on other operations',
'2758': 'Other deposits and guarantees',
'276': 'Accrued interest on financial assets',
'2761': 'Accrued interest on non-trading loans and receivables',
'2762': 'Accrued interest on loans to employees',
'2763': 'Accrued interest on receivables from the State',
'2764': 'Accrued interest on long-term investment securities',
'2765': 'Accrued interest on deposits and guarantees paid',
'2766': 'Accrued interest on finance lease receivables',
'2767': 'Accrued interest on receivables related to participations',
'2768': 'Accrued interest on sundry financial assets',
'277': 'Receivables related to participations and advances to economic interest groupings',
'2771': 'Receivables related to participations, group',
'2772': 'Receivables related to participations, outside the group',
'2773': 'Receivables related to joint ventures',
'2774': 'Advances to economic interest groupings',
'281': 'Accumulated depreciation of intangible assets',
'2811': 'Accumulated depreciation of development costs',
'2812': 'Accumulated depreciation of patents, licences, concessions and similar rights',
'2813': 'Accumulated depreciation of software and websites',
'2814': 'Accumulated depreciation of trademarks',
'2815': 'Accumulated depreciation of goodwill',
'2816': 'Accumulated depreciation of leasehold rights',
'2817': 'Accumulated depreciation of formation costs',
'2818': 'Accumulated depreciation of other intangible assets',
'282': 'Accumulated depreciation of land',
'2824': 'Accumulated depreciation of land development works',
'283': 'Accumulated depreciation of buildings, technical installations and fittings',
'2831': 'Accumulated depreciation of buildings on own land',
'2832': 'Accumulated depreciation of buildings on third-party land',
'2833': 'Accumulated depreciation of infrastructure works',
'2834': 'Accumulated depreciation of fittings, improvements and technical installations',
'2835': 'Accumulated depreciation of office fittings',
'2837': 'Accumulated depreciation of buildings under concession',
'2838': 'Accumulated depreciation of other installations and fittings',
'284': 'Accumulated depreciation of equipment',
'2841': 'Accumulated depreciation of industrial and commercial plant and equipment',
'2842': 'Accumulated depreciation of agricultural plant and equipment',
'2843': 'Accumulated depreciation of returnable and identifiable packaging',
'2844': 'Accumulated depreciation of equipment and furniture',
'2845': 'Accumulated depreciation of transport equipment',
'2846': 'Accumulated depreciation of biological assets',
'2847': 'Accumulated depreciation of fittings and improvements to equipment and biological assets',
'2848': 'Accumulated depreciation of other equipment',
'291': 'Impairment of intangible assets',
'2911': 'Impairment of development costs',
'2912': 'Impairment of patents, licences, trademarks, concessions and similar rights',
'2913': 'Impairment of software and websites',
'2914': 'Impairment of trademarks',
'2915': 'Impairment of goodwill',
'2916': 'Impairment of leasehold rights',
'2917': 'Impairment of formation costs',
'2918': 'Impairment of other intangible rights and assets',
'2919': 'Impairment of intangible assets in progress',
'292': 'Impairment of land',
'2921': 'Impairment of agricultural and forestry land',
'2922': 'Impairment of undeveloped land',
'2923': 'Impairment of land with buildings',
'2924': 'Impairment of land development works',
'2925': 'Impairment of mineral deposit land',
'2926': 'Impairment of developed land',
'2927': 'Impairment of land under concession',
'2928': 'Impairment of other land',
'2929': 'Impairment of land improvements in progress',
'293': 'Impairment of buildings, technical installations and fittings',
'2931': 'Impairment of buildings on own land',
'2932': 'Impairment of buildings on third-party land',
'2933': 'Impairment of infrastructure works',
'2934': 'Impairment of fittings, improvements and technical installations',
'2935': 'Impairment of office fittings',
'2937': 'Impairment of buildings under concession',
'2938': 'Impairment of other installations and fittings',
'2939': 'Impairment of buildings and installations in progress',
'294': 'Impairment of equipment, furniture and biological assets',
'2941': 'Impairment of industrial and commercial plant and equipment',
'2942': 'Impairment of agricultural plant and equipment',
'2943': 'Impairment of returnable and identifiable packaging',
'2944': 'Impairment of equipment and furniture',
'2945': 'Impairment of transport equipment',
'2946': 'Impairment of biological assets',
'2947': 'Impairment of fittings and improvements to equipment and biological assets',
'2948': 'Impairment of other equipment',
'2949': 'Impairment of equipment in progress',
'295': 'Impairment of advances and deposits on non-current assets',
'2951': 'Impairment of advances and deposits on intangible assets',
'2952': 'Impairment of advances and deposits on tangible assets',
'296': 'Impairment of investment securities in participating interests',
'2961': 'Impairment of participations in exclusively controlled companies',
'2962': 'Impairment of participations in jointly controlled companies',
'2963': 'Impairment of participations in companies under significant influence',
'2965': 'Impairment of participations in professional organisations',
'2966': 'Impairment of interests in economic interest groupings',
'2968': 'Impairment of other participating interests',
'297': 'Impairment of other financial assets',
'2971': 'Impairment of loans and receivables',
'2972': 'Impairment of loans to employees',
'2973': 'Impairment of receivables from the State',
'2974': 'Impairment of long-term investment securities',
'2975': 'Impairment of deposits and guarantees paid',
'2977': 'Impairment of receivables related to participations and advances to economic interest groupings',
'2978': 'Impairment of sundry financial receivables',

# ---- 类别 3 存货 ----
'335': 'Packaging',
'3351': 'Non-returnable packaging',
'3352': 'Returnable non-identifiable packaging',
'3353': 'Mixed-use packaging',
'3358': 'Other packaging',
'372': 'Residual products',
'3721': 'Scrap',
'3722': 'Rejects',
'3723': 'Recovered materials',
'387': 'Inventory on consignment or on deposit',
'3871': 'Inventory on consignment',
'3872': 'Inventory on deposit',

# ---- 类别 4 往来方 ----
'401': 'Suppliers, trade payables',
'4011': 'Suppliers',
'4012': 'Group suppliers',
'4013': 'Subcontractor suppliers',
'4017': 'Suppliers, guarantee retentions',
'402': 'Suppliers, notes payable',
'4021': 'Suppliers, notes payable',
'4022': 'Group suppliers, notes payable',
'4023': 'Subcontractor suppliers, notes payable',
'408': 'Suppliers, invoices not received',
'4081': 'Suppliers, invoices not received',
'4082': 'Group suppliers, invoices not received',
'4083': 'Subcontractor suppliers, invoices not received',
'4086': 'Suppliers, accrued interest',
'409': 'Suppliers, debit balances',
'4091': 'Advances and deposits paid to suppliers',
'4092': 'Advances and deposits paid to group suppliers',
'4093': 'Advances and deposits paid to subcontractor suppliers',
'4094': 'Receivables for packaging and materials to be returned',
'4098': 'Rebates, discounts and other credit notes to be obtained',
'411': 'Customers, trade receivables',
'4111': 'Customers',
'4112': 'Group customers',
'4114': 'Customers, State and public authorities',
'4115': 'Customers, international organisations',
'4116': 'Customers, sales with retention of title',
'4117': 'Customers, guarantee retentions',
'4118': 'Customers, value added tax rebates',
'412': 'Customers, notes receivable held in portfolio',
'4121': 'Customers, notes receivable',
'4122': 'Group customers, notes receivable',
'4124': 'State and public authorities, notes receivable',
'4125': 'International organisations, notes receivable',
'4126': 'Customers with retention of title, notes receivable',
'414': 'Receivables on ordinary disposals of non-current assets',
'4141': 'Receivables on account',
'4142': 'Notes receivable',
'416': 'Doubtful or disputed customer receivables',
'4161': 'Disputed receivables',
'4162': 'Doubtful receivables',
'418': 'Customers, income receivable',
'4181': 'Customers, invoices to be issued',
'4186': 'Customers, accrued interest',
'419': 'Customers, credit balances',
'4191': 'Advances and deposits received from customers',
'4192': 'Advances and deposits received from group customers',
'4194': 'Liabilities for packaging and materials held on consignment',
'4198': 'Rebates, discounts and other credit notes to be granted',
'421': 'Employees, advances and down payments',
'4211': 'Employee advances',
'4212': 'Employee down payments',
'4213': 'Expenses advanced and supplies to employees',
'423': 'Employees, attachments and garnishments',
'4231': 'Employee attachments',
'4232': 'Employee wage garnishments',
'4233': 'Third-party holder notices',
'424': 'Internal employee welfare schemes',
'4241': 'Medical assistance',
'4242': 'Family allowances',
'4245': 'Social organisations attached to the entity',
'4248': 'Other internal welfare schemes',
'425': 'Employee representatives',
'4251': 'Employee delegates',
'4252': 'Trade unions and works councils',
'4258': 'Other employee representatives',
'426': 'Employee profit sharing and capital participation',
'4261': 'Profit sharing',
'4264': 'Capital participation',
'428': 'Employees, accrued charges and accrued income',
'4281': 'Provision for holiday pay',
'4286': 'Other accrued charges',
'4287': 'Accrued income',
'431': 'Social security',
'4311': 'Family benefits',
'4312': 'Work accident insurance',
'4313': 'Statutory pension fund',
'4314': 'Voluntary pension fund',
'4318': 'Other social security contributions',
'433': 'Other social organisations',
'4331': 'Mutual insurance society',
'4332': 'Retirement insurance',
'4333': 'Health insurance and health organisations',
'438': 'Social organisations, accrued charges and accrued income',
'4381': 'Social charges on bonuses payable',
'4382': 'Social charges on holiday pay',
'4386': 'Other accrued charges',
'4387': 'Accrued income',
'442': 'State, other taxes and duties',
'4421': 'State taxes and duties',
'4422': 'Taxes and duties for public authorities',
'4423': 'Taxes and duties recoverable from bondholders',
'4424': 'Taxes and duties recoverable from shareholders',
'4426': 'Customs duties',
'4428': 'Other taxes and duties',
'443': 'State, output value added tax invoiced',
'4431': 'Output value added tax on sales',
'4432': 'Output value added tax on services',
'4433': 'Output value added tax on works',
'4434': 'Output value added tax on production delivered to own use',
'4435': 'Value added tax on invoices to be issued',
'444': 'State, value added tax payable or value added tax credit',
'4441': 'Value added tax payable',
'4449': 'Value added tax credit to be carried forward',
'445': 'State, input value added tax recoverable',
'4451': 'Input value added tax on non-current assets',
'4452': 'Input value added tax on purchases',
'4453': 'Input value added tax on transport',
'4454': 'Input value added tax on external services and other charges',
'4455': 'Input value added tax on invoices not received',
'4456': 'Value added tax transferred by other entities',
'447': 'State, taxes withheld at source',
'4471': 'General income tax',
'4472': 'Payroll taxes',
'4473': 'National contribution',
'4474': 'National solidarity contribution',
'4478': 'Other taxes and contributions',
'448': 'State, accrued charges and accrued income',
'4486': 'Accrued charges',
'4487': 'Accrued income',
'449': 'State, sundry receivables and payables',
'4491': 'Guaranteed bonds',
'4492': 'Advances and deposits paid on taxes',
'4493': 'Endowment funds receivable',
'4494': 'Equipment grants receivable',
'4495': 'Operating grants receivable',
'4496': 'Equalisation subsidies receivable',
'4497': 'Advances on subsidies',
'4499': 'Provisioned regulated funds',
'45': 'International organisations',
'451': 'Transactions with African organisations',
'458': 'International organisations, endowment funds and subsidies receivable',
'4581': 'Endowment funds receivable',
'4582': 'Subsidies receivable',
'461': 'Contributors, capital transactions',
'4611': 'Contributions in kind',
'4612': 'Cash contributions',
'4613': 'Subscribed capital called up but not paid',
'4614': 'Capital called up but not paid',
'4615': 'Payments received on capital increase',
'4616': 'Advance payments',
'4617': 'Defaulting contributors',
'4618': 'Other contributions',
'4619': 'Capital to be repaid',
'462': 'Shareholders, current accounts',
'4621': 'Principal',
'4626': 'Accrued interest',
'471': 'Sundry debtors and creditors',
'4711': 'Sundry debtors',
'4712': 'Sundry creditors',
'4713': 'Bondholders',
'4714': 'Receivables on disposals of marketable securities',
'4715': 'Directors remuneration',
'4716': 'Factor account',
'4717': 'Sundry debtors, guarantee retentions',
'4718': 'Contribution, restructuring account',
'4719': 'Share and bond subscription warrants',
'473': 'Intermediaries, transactions on behalf of third parties',
'4731': 'Principals',
'4732': 'Agents',
'4733': 'Consignors',
'4734': 'Commission agents',
'474': 'Periodic allocation of charges and income',
'4746': 'Charges',
'4747': 'Income',
'475': 'Transitional account, special adjustment related to the SYSCOHADA revision',
'4751': 'Asset account',
'4752': 'Liability account',
'478': 'Foreign exchange differences, assets',
'4781': 'Decrease in receivables',
'4782': 'Increase in payables',
'4788': 'Differences offset by forward exchange cover',
'479': 'Foreign exchange differences, liabilities',
'4791': 'Increase in receivables',
'4792': 'Decrease in payables',
'4798': 'Differences offset by forward exchange cover',
'481': 'Suppliers of non-current assets',
'4811': 'Intangible assets',
'4812': 'Tangible assets',
'4817': 'Guarantee retentions',
'4818': 'Invoices not received',
'485': 'Receivables on disposals of non-current assets',
'4851': 'On account',
'4852': 'Notes receivable',
'4857': 'Guarantee retentions',
'4858': 'Invoices to be issued',
'491': 'Impairment of customer accounts',
'4911': 'Disputed receivables',
'4912': 'Doubtful receivables',
})

FIX.update({
# ---- 类别 4（续）、5 资金 ----
'496': 'Impairment of contributor, shareholder and group accounts',
'4962': 'Shareholders, current accounts',
'4963': 'Shareholders, joint operations',
'4966': 'Group, current accounts',
'498': 'Impairment of non-ordinary activity receivable accounts',
'4981': 'Receivables on disposals of non-current assets',
'4982': 'Receivables on disposals of marketable securities',
'4983': 'Other non-ordinary activity receivables',
'499': 'Provisions for short-term risks',
'4991': 'On operating activities',
'4997': 'On financial activities',
'4998': 'On non-ordinary activities',
'501': 'Treasury bills and short-term deposit notes',
'5011': 'Short-term treasury bills',
'5012': 'Financial institution securities',
'5013': 'Short-term deposit notes',
'5016': 'Acquisition costs of treasury bills and deposit notes',
'502': 'Shares',
'5021': 'Own shares or units',
'5022': 'Listed shares',
'5023': 'Unlisted shares',
'5024': 'Split shares, investment certificates and voting rights',
'5025': 'Other shares',
'5026': 'Share acquisition costs',
'503': 'Bonds',
'5031': 'Bonds issued and repurchased by the company',
'5032': 'Listed bonds',
'5033': 'Unlisted bonds',
'5035': 'Other bonds',
'5036': 'Bond acquisition costs',
'504': 'Subscription warrants',
'5042': 'Share subscription warrants',
'5043': 'Bond subscription warrants',
'506': 'Accrued interest on marketable securities',
'5061': 'Accrued interest on treasury bills and deposit notes',
'5062': 'Accrued dividends on shares',
'5063': 'Accrued interest on bonds',
'518': 'Other items in collection',
'5181': 'Warehouse warrants',
'5182': 'Promissory notes',
'5185': 'Travellers cheques',
'5186': 'Matured coupons',
'5187': 'Matured bond interest',
'526': 'Banks, accrued interest',
'5261': 'Banks, accrued interest payable',
'5267': 'Banks, accrued interest receivable',
'536': 'Financial institutions, accrued interest',
'5361': 'Financial institutions, accrued interest payable',
'5367': 'Financial institutions, accrued interest receivable',
'571': 'Cash on hand at head office',
'5711': 'In legal currency',
'5712': 'In foreign currency',
'572': 'Cash on hand at branch A',
'5721': 'In legal currency',
'5722': 'In foreign currency',
'573': 'Cash on hand at branch B',
'5731': 'In legal currency',
'5732': 'In foreign currency',

# ---- 类别 6 费用 ----
'601': 'Purchases of merchandise',
'6011': 'Within the Region',
'6012': 'Outside the Region',
'6013': 'From group entities within the Region',
'6014': 'From group entities outside the Region',
'6015': 'Purchases of merchandise, incidental expenses',
'6019': 'Rebates, discounts and allowances obtained, not allocated',
'602': 'Purchases of raw materials and related supplies',
'6021': 'Within the Region',
'6022': 'Outside the Region',
'6023': 'From group entities within the Region',
'6024': 'From group entities outside the Region',
'6025': 'Purchases of raw materials, incidental expenses',
'6029': 'Rebates, discounts and allowances obtained, not allocated',
'603': 'Changes in inventories of purchased goods',
'6031': 'Changes in merchandise inventories',
'6032': 'Changes in raw material and supply inventories',
'6033': 'Changes in other supply inventories',
'604': 'Purchases of consumable materials and supplies',
'6041': 'Consumable materials',
'6042': 'Fuel materials',
'6043': 'Maintenance products',
'6044': 'Workshop and factory supplies',
'6045': 'Purchases of consumables, incidental expenses',
'6046': 'Store supplies',
'6047': 'Office supplies',
'6049': 'Rebates, discounts and allowances obtained, not allocated',
'605': 'Other purchases',
'6051': 'Non-storable supplies, water',
'6052': 'Non-storable supplies, electricity',
'6053': 'Non-storable supplies, other energy',
'6054': 'Non-storable maintenance supplies',
'6055': 'Non-storable office supplies',
'6056': 'Purchases of small equipment and tools',
'6057': 'Purchases of studies and services',
'6058': 'Purchases of works, materials and equipment',
'6059': 'Rebates, discounts and allowances obtained, not allocated',
'608': 'Purchases of packaging',
'6081': 'Non-returnable packaging',
'6082': 'Returnable non-identifiable packaging',
'6083': 'Mixed-use packaging',
'6085': 'Purchases of packaging, incidental expenses',
'6089': 'Rebates, discounts and allowances obtained, not allocated',
'618': 'Other transport costs',
'6181': 'Travel and business trips',
'6182': 'Transport between establishments or sites',
'6183': 'Transport between establishments or sites',
'622': 'Rentals and lease charges',
'6221': 'Land rentals',
'6222': 'Building rentals',
'6223': 'Equipment and tool rentals',
'6224': 'Losses on packaging',
'6225': 'Packaging rentals',
'6226': 'Farm leases and land rents',
'6228': 'Sundry rentals and lease charges',
'623': 'Lease-purchase royalties',
'6232': 'Property finance leases',
'6233': 'Movable finance leases',
'6234': 'Hire purchase',
'6235': 'Other lease-purchase contracts',
'624': 'Maintenance, repairs and servicing',
'6241': 'Maintenance and repairs of buildings',
'6242': 'Maintenance and repairs of movable assets',
'6243': 'Servicing',
'6248': 'Other maintenance and repairs',
'625': 'Insurance premiums',
'6251': 'Multi-risk insurance',
'6252': 'Transport equipment insurance',
'6253': 'Operating risk insurance',
'6254': 'Product liability insurance',
'6255': 'Customer insolvency insurance',
'6257': 'Sales transport insurance',
'6258': 'Other insurance premiums',
'626': 'Studies, research and documentation',
'6261': 'Studies and research',
'6265': 'General documentation',
'6266': 'Technical documentation',
'627': 'Advertising, publications and public relations',
'6271': 'Announcements and press insertions',
'6272': 'Catalogues and advertising printed matter',
'6273': 'Samples',
'6274': 'Trade fairs and exhibitions',
'6275': 'Publications',
'6276': 'Gifts to customers',
'6277': 'Symposium, seminar and conference costs',
'6278': 'Other advertising and public relations costs',
'628': 'Telecommunication costs',
'6281': 'Telephone costs',
'6282': 'Telex costs',
'6283': 'Fax costs',
'6288': 'Other telecommunication costs',
'631': 'Bank charges',
'6311': 'Securities charges, sale and custody',
'6312': 'Charges on notes',
'6313': 'Safe deposit box rental',
'6314': 'Factoring commissions',
'6315': 'Credit card commissions',
'6316': 'Loan issuance costs',
'6317': 'Electronic money instrument charges',
'6318': 'Other bank charges',
'632': 'Fees of intermediaries and advisers',
'6322': 'Sales commissions and brokerage',
'6324': 'Fees of regulated professions',
'6325': 'Legal and litigation costs',
'6327': 'Fees of other service providers',
'6328': 'Sundry fees',
'634': 'Royalties for patents, licences, trademarks, software, websites and similar rights',
'6342': 'Royalties for patents and licences',
'6343': 'Royalties for software',
'6344': 'Royalties for trademarks',
'6345': 'Royalties for websites',
'6346': 'Royalties for concessions and similar rights and assets',
'635': 'Subscriptions and contributions',
'6351': 'Subscriptions and contributions',
'6358': 'Sundry sponsorships',
'637': 'Remuneration of staff external to the entity',
'6371': 'Temporary staff',
'6372': 'Seconded or loaned staff',
'638': 'Other external charges',
'6381': 'Staff recruitment costs',
'6382': 'Removal costs',
'6383': 'Entertainment',
'6384': 'Assignment expenses',
'641': 'Direct taxes and duties',
'6411': 'Property taxes and related taxes',
'6412': 'Business licences and related taxes',
'6413': 'Taxes on salaries and wages',
'6414': 'Apprenticeship tax',
'6415': 'Continuing vocational training levy',
'6418': 'Other direct taxes',
'646': 'Registration duties',
'6461': 'Transfer duties',
'6462': 'Stamp duties',
'6463': 'Company vehicle taxes',
'6464': 'Vehicle tax discs',
'6468': 'Other duties',
'647': 'Tax penalties and fines',
'6471': 'Assessment penalties on direct taxes',
'6472': 'Assessment penalties on indirect taxes',
'6473': 'Collection penalties on direct taxes',
'6474': 'Collection penalties on indirect taxes',
'6478': 'Other criminal and tax fines',
'651': 'Losses on customer and other receivables',
'6511': 'Customers',
'6515': 'Other debtors',
'652': 'Share of results on joint operations',
'6521': 'Share of profits transferred, managing partner books',
'6525': 'Losses allocated by transfer, non-managing partner books',
'658': 'Sundry charges',
'6581': 'Directors fees and other remuneration',
'6582': 'Donations',
'6583': 'Patronage',
'6588': 'Other sundry charges',
'659': 'Operating impairment losses and short-term risk provisions',
'6591': 'On short-term risks',
'6593': 'On inventories',
'6594': 'On receivables',
'6598': 'Other operating impairment losses and short-term risk provisions',
'661': 'Direct remuneration paid to national staff',
'6611': 'Salaries, wages and commissions',
'6612': 'Bonuses and gratuities',
'6613': 'Paid leave',
'6614': 'Notice, redundancy and job search compensation',
'6615': 'Sick pay to employees',
'6616': 'Family supplement',
'6617': 'Benefits in kind',
'6618': 'Other direct remuneration',
'662': 'Direct remuneration paid to non-national staff',
'6621': 'Salaries, wages and commissions',
'6622': 'Bonuses and gratuities',
'6623': 'Paid leave',
'6624': 'Notice, redundancy and job search compensation',
'6625': 'Sick pay to employees',
'6626': 'Family supplement',
'6627': 'Benefits in kind',
'6628': 'Other direct remuneration',
'663': 'Flat-rate allowances paid to staff',
'6631': 'Housing allowances',
'6632': 'Entertainment allowances',
'6633': 'Expatriation allowances',
'6638': 'Other allowances and benefits',
'664': 'Social charges',
'6641': 'Social charges on national staff remuneration',
'6642': 'Social charges on non-national staff remuneration',
'666': 'Remuneration and social charges of the sole proprietor',
'6661': 'Remuneration for the work of the proprietor',
'6662': 'Social charges',
'667': 'Remuneration transferred for external staff',
'6671': 'Temporary staff',
'6672': 'Seconded or loaned staff',
'668': 'Other social charges',
'6681': 'Payments to trade unions and works councils',
'6682': 'Payments to health and safety committees',
'6683': 'Payments to other welfare schemes',
'6684': 'Occupational medicine and pharmacy',
'6685': 'Health insurance and health organisations',
'6686': 'Retirement insurance and pension funds',
'671': 'Interest on borrowings',
'6711': 'On bond borrowings',
'6712': 'On borrowings from credit institutions',
'6713': 'On liabilities related to participations',
'6714': 'On bond redemption premiums',
'672': 'Interest in lease-purchase payments',
'6721': 'Interest in property finance lease payments',
'6722': 'Interest in movable finance lease payments',
'6723': 'Interest in hire purchase payments',
'6724': 'Interest in other lease contract payments',
'674': 'Other interest',
'6741': 'On advances received and credit deposits',
'6742': 'On blocked current accounts',
'6743': 'On guaranteed bonds',
'6744': 'On trade payables',
'6745': 'Bank interest and interest on cash and discount operations',
'6748': 'On sundry payables',
'677': 'Losses on marketable securities',
'6771': 'Losses on disposals of marketable securities',
'6772': 'Losses on free share allocations to employees and managers',
'678': 'Losses on financial risks',
'6781': 'On life annuities',
'6782': 'On financial transactions',
'6784': 'On cash management instruments',
'679': 'Financial impairment losses and short-term risk provisions',
'6791': 'On financial risks',
'6795': 'On marketable securities',
'6798': 'Other financial impairment losses and short-term risk provisions',
'681': 'Operating depreciation and amortisation charges',
'6812': 'Depreciation of intangible assets',
'6813': 'Depreciation of tangible assets',
'691': 'Operating provisions',
'6911': 'For risks and charges',
'6913': 'For impairment of intangible assets',
'6914': 'For impairment of tangible assets',
'697': 'Financial provisions',
'6971': 'For risks and charges',
'6972': 'For impairment of financial assets',

# ---- 类别 7 收入 ----
'701': 'Sales of merchandise',
'7011': 'Within the Region',
'7012': 'Outside the Region',
'7013': 'To group entities within the Region',
'7014': 'To group entities outside the Region',
'7015': 'Over the internet',
'702': 'Sales of finished goods',
'7021': 'Within the Region',
'7022': 'Outside the Region',
'7023': 'To group entities within the Region',
'7024': 'To group entities outside the Region',
'7025': 'Over the internet',
'703': 'Sales of semi-finished goods',
'7031': 'Within the Region',
'7032': 'Outside the Region',
'7033': 'To group entities within the Region',
'7034': 'To group entities outside the Region',
'7035': 'Over the internet',
'704': 'Sales of residual products',
'7041': 'Within the Region',
'7042': 'Outside the Region',
'7043': 'To group entities within the Region',
'7044': 'To group entities outside the Region',
'7045': 'Over the internet',
'705': 'Work billed',
'7051': 'Within the Region',
'7052': 'Outside the Region',
'7053': 'To group entities within the Region',
'7054': 'To group entities outside the Region',
'7055': 'Over the internet',
'706': 'Services sold',
'7061': 'Within the Region',
'7062': 'Outside the Region',
'7063': 'To group entities within the Region',
'7064': 'To group entities outside the Region',
'7065': 'Over the internet',
'707': 'Ancillary income',
'7071': 'Postage, non-returnable packaging and other invoiced costs',
'7072': 'Commissions and brokerage',
'7073': 'Rentals',
'7074': 'Gains on returns and disposals of packaging',
'7075': 'Secondment of staff',
'7076': 'Royalties for patents, software, trademarks and similar rights',
'7077': 'Services operated for the benefit of staff',
'7078': 'Other ancillary income',
'718': 'Other operating grants',
'7181': 'Paid by the State and public authorities',
'7182': 'Paid by international organisations',
'7183': 'Paid by third parties',
'734': 'Changes in work in progress inventories',
'7341': 'Goods in progress',
'7342': 'Construction work in progress',
'735': 'Changes in services in progress',
'7351': 'Studies in progress',
'7352': 'Services in progress',
'737': 'Changes in semi-finished and residual product inventories',
'7371': 'Semi-finished products',
'7372': 'Residual products',
'752': 'Share of results on joint operations',
'7521': 'Share of losses transferred, managing partner books',
'7525': 'Profits allocated by transfer, non-managing partner books',
'758': 'Sundry income',
'7581': 'Directors fees and other remuneration',
'7582': 'Insurance claims received',
'7588': 'Other sundry income',
'759': 'Reversals of operating accrued charges',
'7591': 'On short-term risks',
'7593': 'On inventories',
'7594': 'On receivables',
'7598': 'On other accrued charges',
'771': 'Interest on loans and sundry receivables',
'7712': 'Interest on loans',
'7713': 'Interest on sundry receivables',
'772': 'Income from participations and other long-term receivables',
'7721': 'Income from participating interests',
'7722': 'Income from other long-term investment securities',
'774': 'Investment income',
'7745': 'Income from bonds',
'7746': 'Income from marketable securities',
'775': 'Interest in lease-purchase payments',
'778': 'Gains on financial risks',
'7781': 'On life annuities',
'7782': 'On financial transactions',
'7784': 'On cash management instruments',
'779': 'Reversals of financial accrued charges',
'7791': 'On financial risks',
'7795': 'On marketable securities',
'7798': 'On other accrued financial charges',
'791': 'Reversals of operating provisions',
'7911': 'For risks and charges',
'7913': 'For impairment of intangible assets',
'7914': 'For impairment of tangible assets',
'797': 'Reversals of financial provisions',
'7971': 'For risks and charges',
'7972': 'For impairment of financial assets',

# ---- 类别 8、9 ----
'891': 'Income tax for the year',
'8911': 'Activities carried out in the home State',
'8912': 'Activities carried out in other States of the Region',
'8913': 'Activities carried out outside the Region',
'899': 'Tax relief and cancellations of prior-year income tax',
'8991': 'Tax relief',
'8994': 'Cancellations for retroactive losses',
'901': 'Financing commitments obtained',
'9011': 'Confirmed credit lines obtained',
'9012': 'Borrowings remaining to be drawn',
'9013': 'Revolving financing facilities',
'9014': 'Issuance facilities',
'9018': 'Other financing commitments obtained',
'902': 'Guarantee commitments obtained',
'9021': 'Endorsements obtained',
'9022': 'Guarantees obtained',
'9023': 'Mortgages obtained',
'9024': 'Notes endorsed by third parties',
'9028': 'Other guarantees obtained',
'903': 'Reciprocal commitments',
'9031': 'Forward purchases of merchandise',
'9032': 'Forward purchases of foreign currency',
'9033': 'Firm orders from customers',
'9038': 'Other reciprocal commitments',
'904': 'Other commitments obtained',
'9041': 'Conditional debt waivers',
'9043': 'Sales with retention of title clauses',
'9048': 'Sundry commitments obtained',
'905': 'Financing commitments granted',
'9051': 'Credit granted but not drawn',
'9058': 'Other financing commitments granted',
'906': 'Guarantee commitments granted',
'9061': 'Endorsements granted',
'9062': 'Guarantees granted',
'9063': 'Mortgages granted',
'9064': 'Notes endorsed by the entity',
'9068': 'Other guarantees granted',
'907': 'Reciprocal commitments granted',
'9071': 'Forward sales of merchandise',
'9072': 'Forward sales of foreign currency',
'9073': 'Firm orders to suppliers',
'9078': 'Other reciprocal commitments granted',
'908': 'Other commitments granted',
'9081': 'Conditional cancellations of debts',
'9082': 'Retirement commitments',
'9083': 'Purchases with retention of title clauses',
'9088': 'Sundry commitments granted',
})

# ---- 非重复组中已确认的错译 / 含混译名 ----
FIX.update({
'10': 'Capital',
'17': 'Lease-purchase liabilities',
'172': 'Lease-purchase liabilities on property finance leases',
'173': 'Lease-purchase liabilities on movable finance leases',
'174': 'Lease-purchase liabilities on hire purchase',
'178': 'Liabilities on other lease-purchase contracts',
'182': 'Liabilities related to joint ventures',
'183': 'Accrued interest on liabilities related to participations',
'184': 'Blocked permanent accounts of branches and agencies',
'185': 'Non-blocked permanent accounts of branches and agencies',
'186': 'Liaison accounts, expenses',
'162': 'Borrowings and debts owed to credit institutions',
'109': 'Contributors, capital subscribed but not called up',
'42': 'Personnel',
'452': 'Transactions with other international organisations',
'463': 'Shareholders, joint operations',
'466': 'Group, current accounts',
'467': 'Contributors, balance due on called-up capital',
'472': 'Payments remaining to be made on unpaid marketable securities',
'482': 'Suppliers of non-current assets, notes payable',
'483': 'Liabilities on acquisition of marketable securities',
'486': 'Receivables on disposals of marketable securities',
'488': 'Other non-ordinary activity receivables',
'53': 'Financial institutions and similar organisations',
'533': 'Management and brokerage companies',
'538': 'Other financial institutions',
'511': 'Notes to be collected',
'512': 'Notes in collection',
'524': 'Banks outside the monetary zone',
'543': 'Equity index options',
'544': 'Forward market instruments',
'545': 'Holdings of gold and other precious metals',
'552': 'Electronic money, mobile phone',
'553': 'Electronic money, toll card',
'554': 'Electronic wallets',
'56': 'Bank cash and discount credits',
'561': 'Cash credits',
'564': 'Discount of seasonal credits',
'565': 'Discount of ordinary credits',
'566': 'Bank cash credits, accrued interest',
'58': 'Imprest accounts, letters of credit and internal transfers',
'581': 'Imprest accounts',
'582': 'Letters of credit',
'588': 'Other internal transfers',
'593': 'Impairment of financial institution accounts',
'594': 'Impairment of cash management instruments',
'599': 'Provisions for financial risks',
'68': 'Depreciation and amortisation charges',
'69': 'Charges to provisions',
'70': 'Sales',
'83': 'Non-ordinary activity expenses',
'837': 'Expenses related to liquidation operations',
'839': 'Charges for impairment and short-term risk provisions',
'84': 'Non-ordinary activity income',
'845': 'Donations and gifts received',
'846': 'Debt waivers obtained',
'847': 'Income related to liquidation operations',
'849': 'Reversals of impairment charges and short-term risk provisions',
'85': 'Non-ordinary activity allocations',
'87': 'Employee profit sharing',
'872': 'Contractual profit sharing',
'878': 'Other profit sharing',
'88': 'Equalisation subsidies',
'881': 'State',
'884': 'Public authorities',
'886': 'Group',
'888': 'Other',
'89': 'Income tax',
'892': 'Back assessments of prior-year income tax',
'895': 'Minimum flat-rate tax',
'90': 'Commitments obtained and commitments granted',
'91': 'Counterpart accounts for commitments',
})

# ---- 二轮消歧：法文不同但英文仍撞车 ----
FIX.update({
'1684': 'Participating borrowings',
'4493': 'State, endowment funds receivable',
'4581': 'International organisations, endowment funds receivable',
'6011': 'Merchandise purchased within the Region',
'6012': 'Merchandise purchased outside the Region',
'6013': 'Merchandise purchased from group entities within the Region',
'6014': 'Merchandise purchased from group entities outside the Region',
'6021': 'Raw materials purchased within the Region',
'6022': 'Raw materials purchased outside the Region',
'6023': 'Raw materials purchased from group entities within the Region',
'6024': 'Raw materials purchased from group entities outside the Region',
'7011': 'Merchandise sold within the Region',
'7012': 'Merchandise sold outside the Region',
'7013': 'Merchandise sold to group entities within the Region',
'7014': 'Merchandise sold to group entities outside the Region',
'7021': 'Finished goods sold within the Region',
'7022': 'Finished goods sold outside the Region',
'7023': 'Finished goods sold to group entities within the Region',
'7024': 'Finished goods sold to group entities outside the Region',
'7031': 'Semi-finished goods sold within the Region',
'7032': 'Semi-finished goods sold outside the Region',
'7033': 'Semi-finished goods sold to group entities within the Region',
'7034': 'Semi-finished goods sold to group entities outside the Region',
'7041': 'Residual products sold within the Region',
'7042': 'Residual products sold outside the Region',
'7043': 'Residual products sold to group entities within the Region',
'7044': 'Residual products sold to group entities outside the Region',
'7051': 'Work billed within the Region',
'7052': 'Work billed outside the Region',
'7053': 'Work billed to group entities within the Region',
'7054': 'Work billed to group entities outside the Region',
'7061': 'Services sold within the Region',
'7062': 'Services sold outside the Region',
'7063': 'Services sold to group entities within the Region',
'7064': 'Services sold to group entities outside the Region',
'6591': 'On short-term operating risks',
'6593': 'On inventories',
'6594': 'On receivables',
'6598': 'On other operating items',
'7591': 'Reversals on short-term risks',
'7593': 'Reversals on inventories',
'7594': 'Reversals on receivables',
'7598': 'Reversals on other accrued charges',
})


import re as _re
_CJK_TAIL = _re.compile(r'[\u4e00-\u9fff\u3400-\u4dbf\u3000-\u303f\uff00-\uffef]+')


def strip_cn(en: str) -> str:
    """剥离英文列中冗余的「— 中文译文」尾巴（中文列已单独展示，此处纯属重复）。"""
    t = _CJK_TAIL.sub(' ', en)
    t = _re.sub(r'\s*[-–—]\s*$', '', t)
    t = _re.sub(r'\s{2,}', ' ', t)
    return t.strip(' -–—,')
